name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Build With Maven
        run: mvn clean install
      - uses: actions/upload-artifact@v4
        with:
          name: perworldinventory-kt.jar
          path: target/perworldinventory-kt-*.jar